### PR TITLE
Update sponsor page

### PR DESCRIPTION
**Pull request by james9909**

### CODE REVIEW

**Comment by justinkim** [comment]
There's no need to create a new PR, you can update the existing branch with new history and it will be reflected in the PR.

**Comment by justinkim** [comment]
:package: :ship: :moneybag:

**Comment by james9909** [comment]
Sorry, wasn't sure about the impact of a force push on a pr. I resubmitted the pr just to be safe, but I'll keep this in mind for the future.

**Comment by justinkim** [comment]
@james9909 Delete remote branches after you're done merging.

**Comment by kevinwang** [comment]
FYI, you can also squash and merge PRs directly from GitHub.

**Pull request merged**
