### PR TITLE
Fix navbar highlighting

### PR DESCRIPTION
**Pull request by james9909**
In older versions of jekyll, `page.url` adds `index.html` to the end of the url, resulting in some pages not having their respective navbar sections highlighted.

### CODE REVIEW

**Comment by justinkim** [comment]
@james9909 The build is failing.

**Comment by james9909** [comment]
Yeah I saw, I'll fix it tonight.

**Comment by kevinwang** [comment]
I would rather not change old blog posts and instead ignore `/blog/*`.

**Comment by james9909** [comment]
Alright, will do.

**Pull request closed without merging**
