### PR TITLE
Update ec page

### PR DESCRIPTION
**Pull request by james9909**
These are the changes that marketing wants to make to the ec page.

### CODE REVIEW

**Comment by justinkim** [comment]
The EC descriptions on the website should mirror what is in the charter. The charter descriptions should be updated before the website copy changes.

Also, "he/she" is poor form, singular plural "they" or "he or she" is preferred. The latter stutters a bit more when repeated, so I generally prefer "they."

**Comment by elc1798** [comment]
... Why was I assigned to this...

**Comment by justinkim** [comment]
He made a mistake chill

**Comment by WilsonBerkow** [comment]
I'm with Justin on "he or she" being better form. I would push "they" but we bikeshedded about this and "they" lost.

**Comment by james9909** [comment]
I've forwarded your concerns to marketing, just waiting for a reply.

**Comment by justinkim** [comment]
@james9909 I'm saying that any improvements to the copy on the EC page should be reflected in the copy in the charter. That should be included as part of this PR.

**Comment by james9909** [comment]
From the information I was given by marketing, it appeared that they wanted the ec descriptions on the website to be slightly different from the descriptions in the charter. I am currently sorting things out with marketing and will update the charter once it is finalized, after the "he/she" issue has been resolved.

**Comment by justinkim** [comment]
lgtm :package: :ship: :moneybag:

**Pull request merged**
